### ISSUE TITLE
bind 2 modules

### ISSUE THREAD

**Issue by zz-james** [mkuklis/asEvented#20]
Your example shows a model emitting and bound to the event triggered when ID is updated, I was hoping to bind a view module to listen to the model, can you give an example of 2 seperate modules please?

**Comment by mkuklis** [comment]
@zz-james one way you could accomplish it is to pass a model to your view and add a binding inside the view with the context attached to the view. This is very simplistic example:

````js

function Model() {}

asEvented.call(Model.prototype);

function View(model) {
  model.bind('change', this.update.bind(this));
}

View.prototype.update = function () {
  // executed when 'change' on model is triggered
}

var model = new Mode();
var view = new View(model);


model.trigger('change', 2); 

````

Is this what you were asking for?
