### ISSUE TITLE
Events apply should be FIFO

### ISSUE THREAD

**Issue by garex** [mkuklis/asEvented#24]
```
// Native js
document.addEventListener('click', function() { console.log(1) })
document.addEventListener('click', function() { console.log(2) })

// jQuery
jQuery(document).click(function() { console.log(3) })
jQuery(document).click(function() { console.log(4) })
```

**Result:**

1
2
3
4

But in asEvented [apply order is from last to first](https://github.com/mkuklis/asEvented/blob/fcd9758381b96db6ac8d154d4b4de5a82d632a7c/asevented.js#L74). This is confusing.

1. Why did you choose such order -- LIFO?
2. May be change it to FIFO?

**Comment by mkuklis** [comment]
@garex you are right. I'm not sure if this was intentional. I'm open for pull requests. Do you want to send one?

**Comment by garex** [comment]
@mkuklis ok, I will.

In the meantime you can setup tests in all popular browsers on travis+sause combination.

Pls see this project as example: https://github.com/garex/angular-sorted-map

**Comment by mkuklis** [comment]
@garex cool thanks. I will check it out.

**Comment by garex** [comment]
@mkuklis I sent pr #25 regarding this issue.
